name: build

on:
  push:
    branches: [main]
    tags:
      - "*"
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        platform: [chrome, firefox, figma]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: paulhatch/semantic-version@v5.0.2
        id: semantic
      - run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.semantic.outputs.version }}\"/" public/manifest.${{ matrix.platform }}.json
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.semantic.outputs.version }}\"/" package.json
      - run: npm ci
      - run: npm run build:${{ matrix.platform }}
      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: magic-copy-${{ matrix.platform }}
          path: dist
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          files: magic-copy-${{ matrix.platform }}.zip
